# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd "$(Build.SourcesDirectory)\BankingSimulation.UI\ClientApp"
    npm install
    npm run build
    dir "$(Build.SourcesDirectory)\BankingSimulation.UI\ClientApp"
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\BankingSimulation.UI\ClientApp\build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactsStagingDirectory)'
  
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'