# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '10.2.4'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'
  workingDirectory: $(Build.SourcesDirectory)\BankingSimulation.UI\ClientApp

- script: npm run build
  displayName: 'npm run build'
  workingDirectory: $(Build.SourcesDirectory)\BankingSimulation.UI\ClientApp

- script: dir "$(Build.SourcesDirectory)\BankingSimulation.UI\ClientApp"

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\BankingSimulation.UI\ClientApp\build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactsStagingDirectory)'
  
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'