# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main

pool:
  vmImage: windows-latest

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '20.11.1'
  displayName: 'Install Node.js'
  
- task: PowerShell@2
  displayName: 'Subsitute secrets'
  inputs:
    targetType: 'inline'
    workingDirectory: $(Build.SourcesDirectory)\BankingSimulation.UI\ClientApp\src\config
    script: |
      $(Get-Content ApiConfig.js) -Replace ('__ApiBaseUrl__','$env:apiBaseUrl') -Replace ('__LoginAuthority__', '$env:loginAuthority') | Set-Content -Path ApiConfig.js

- script: npm install
  displayName: 'npm install'
  workingDirectory: $(Build.SourcesDirectory)\BankingSimulation.UI\ClientApp

- script: npm run build
  displayName: 'npm run build'
  workingDirectory: $(Build.SourcesDirectory)\BankingSimulation.UI\ClientApp

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\BankingSimulation.UI\ClientApp\build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'